![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

In [212]:
my_array = np.arange(10)
mask = my_array % 2 == 1
print(my_array[mask][::-1])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [11]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [13]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [7]:
matriz = np.arange(1, 21).reshape(4, 5)
print(matriz)

print(matriz[::-1, ::-1])
print(matriz.T) # Transpuesta
print(np.flip(matriz))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [21]:
nuevo_array = matriz[:2, :2]
print(nuevo_array)

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [29]:
nuevo_array_1 = matriz[::2, ::2]
print(nuevo_array_1)

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [33]:
nuevo_array_2 = matriz[:3:, ::-1]
print(nuevo_array_2)

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [12]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
mask_1 = x == "Loro"
print(x[mask_1])
sol_2 = np.where(x == "Loro", x,"")
sol_3 = np.extract(x == "Loro", x)
print(sol_2)
print(sol_3)

['Loro' 'Loro']
['Loro' '' '' 'Loro' '']
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [42]:
secuencia = np.arange(20)
print(secuencia, end = "\n\n")
secuencia.reshape(2,5,2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]



array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [17]:
cero = np.full(10, 0) # dtype = np.int8 (dtype para forzar el tipo y tamaño, en este caso integer de 8 bits)
print(cero)
print(cero.itemsize, "bytes")
print(cero.nbytes)
print(cero.dtype)
cero[3] = 1
print("4º elemento = 1,", cero)

[0 0 0 0 0 0 0 0 0 0]
8 bytes
80
int64
4º elemento = 1, [0 0 0 1 0 0 0 0 0 0]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [53]:
vector = np.arange(10, 50)
print("Vector del 10 al 49:", vector)
print("Vetor invertido:", vector[::-1])

Vector del 10 al 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Vetor invertido: [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [19]:
def busqueda_indice(vector = [1,2,0,0,4,0]):
    vector_array = np.array(vector)
    sol = np.where(vector_array != 0)[0]
    return sol
busqueda_indice()

array([0, 1, 4])

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [77]:
matriz_random = np.random.randint(100, size = (10,10))
print(matriz_random)
print("Mínimo:", np.min(matriz_random))
print("Máximo:", np.max(matriz_random))

[[67 69 29 94 36 47 80 38 10 23]
 [54  0 92 27 26 96 66  2 57 28]
 [23 26 78 54 24 90 94 34 10  4]
 [66 78 92 91 58 83 94 52 33 60]
 [93 97 16 55 71 18 54 76 83 54]
 [27 75 50 94  6 41 75 64 90  4]
 [26 95 23 63 50 12 29 74 69 14]
 [71  2 72 37 95 25 74 87 37  0]
 [16  3 70 97 24 25 48  3 12 49]
 [85  3 83 13 13 94 86 58 47 63]]
Mínimo: 0
Máximo: 97


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [2]:
aleatorio = np.random.randint(100, size = 30)
print(aleatorio)
print("Media", np.mean(aleatorio))
print("Media hecho con sum/ total", (np.sum(aleatorio) / (len(aleatorio))))


[85 22 11 53 25 97 49 11 88 96 21 59 80 13 94 41 65 46 80 34 31 64 19 12
 39 13 73 21 87 91]
Media 50.666666666666664
Media hecho con sum/ total 50.666666666666664


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [3]:
dosde = np.full((10,10), 0)
print(dosde)
dosde[0] = 1
dosde[-1::] = 1
dosde[0:, :1] = 1
dosde[0:, -1:] = 1 # también se puede hacer con dos slicing que sea haciendo saltos de la longitud del array -1 

print(dosde)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [185]:
matriz_8 = np.full((8,8), 0)

matriz_8[::2, 1::2] = 1
matriz_8[1::2, ::2] = 1
print(matriz_8)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [4]:
matriz_8_2 = np.array([[0, 1,],
                       [1,0]])
print(np.tile(matriz_8_2, (4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [199]:
al_azar = np.random.randint(100, size = (5, 5))
normalizacion = (al_azar - (np.mean(al_azar))) / np.std(al_azar)
print("Los valores normalizados son:\n", normalizacion)

Los valores normalizados son:
 [[ 0.30491586 -1.82069949  0.37821294  0.74469834 -1.71075387]
 [ 1.58761477  0.01172753  1.44102061 -0.35475787  0.48815856]
 [-1.45421408  1.47766915 -0.35475787  0.26826732  0.30491586]
 [-1.23432284  1.33107499 -0.13486663 -0.50135203  0.41486148]
 [ 1.25777791 -0.02492101 -1.67410532 -0.28146079 -0.46470349]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [6]:
secuencia = np.arange(0,11)
print("Secuencia del 0 al 10:", secuencia)

nuevo_array_3 = np.where((secuencia < 8) & (secuencia > 3), -1, secuencia)
print("Nuevo array con -1 del 4 al 7:", nuevo_array_3)
nuevo_array_4 = np.where((secuencia < 8) & (secuencia > 3), secuencia * (-1), secuencia)
print("Nuevo array negando valores del 4 al :", nuevo_array_4)

Secuencia del 0 al 10: [ 0  1  2  3  4  5  6  7  8  9 10]
Nuevo array con -1 del 4 al 7: [ 0  1  2  3 -1 -1 -1 -1  8  9 10]
Nuevo array negando valores del 4 al : [ 0  1  2  3 -4 -5 -6 -7  8  9 10]
